# Paygen Configuration Files
recipes_dir: ~/cyber/paygen/recipes
templates_dir: ~/cyber/paygen/templates
preprocessors_dir: ~/cyber/paygen/preprocessors
ps_obfuscation_yaml: ~/cyber/paygen/ps-obfuscation.yaml
ps_features_yaml: ~/cyber/paygen/ps-features.yaml
shellcodes_config: ~/cyber/paygen/shellcodes.yaml
output_dir: ~/cyber/postex-tools/payloads

# Build preferences
keep_source_files: true # If true, save rendered source code alongside compiled binaries
show_build_debug: true # If true, show real-time command output in build popup

# Web
web_host: '0.0.0.0'
web_port: 1337
web_debug: false